import {
  niyetFunc,
  iftitahFunc,
  kiyamFunc,
  rukuFunc,
  rukuKalkisFunc,
  secdeFunc,
  secdeKalkisFunc,
  oturusFunc,
  sonOturusFunc,
  selamFunc,
} from './rukunFunctions.js';

const sabahSteps = (gender, time) => {
  return [
    niyetFunc(gender, time),
    iftitahFunc(gender),
    kiyamFunc(gender, 1),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    kiyamFunc(gender, 2),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    sonOturusFunc(gender),
    selamFunc(gender),
  ];
};

const ogleSteps = (gender, time) => {
  return [
    niyetFunc(gender, time),
    iftitahFunc(gender),
    kiyamFunc(gender, 1),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    kiyamFunc(gender, 2),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    oturusFunc(gender),
    kiyamFunc(gender, 3),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    kiyamFunc(gender, 4),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    sonOturusFunc(gender),
    selamFunc(gender),
  ];
};

const ikindiSteps = (gender, time) => {
  return [
    niyetFunc(gender, time),
    iftitahFunc(gender),
    kiyamFunc(gender, 1),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    kiyamFunc(gender, 2),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    oturusFunc(gender),
    kiyamFunc(gender, 3),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    kiyamFunc(gender, 4),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    sonOturusFunc(gender),
    selamFunc(gender),
  ];
};

const aksamSteps = (gender, time) => {
  return [
    niyetFunc(gender, time),
    iftitahFunc(gender),
    kiyamFunc(gender, 1),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    kiyamFunc(gender, 2),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    oturusFunc(gender),
    kiyamFunc(gender, 3),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    sonOturusFunc(gender),
    selamFunc(gender),
  ];
};

const yatsiSteps = (gender, time) => {
  return [
    niyetFunc(gender, time),
    iftitahFunc(gender),
    kiyamFunc(gender, 1),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    kiyamFunc(gender, 2),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    oturusFunc(gender),
    kiyamFunc(gender, 3),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    kiyamFunc(gender, 4),
    rukuFunc(gender),
    rukuKalkisFunc(gender),
    secdeFunc(gender),
    secdeKalkisFunc(gender),
    secdeFunc(gender),
    sonOturusFunc(gender),
    selamFunc(gender),
  ];
};

export { sabahSteps, ogleSteps, ikindiSteps, aksamSteps, yatsiSteps };
